name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.3
  percent_indicator: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Tomorrow
      fonts:
        - asset: assets/fonts/Tomorrow-Regular.ttf
    - family: Solway
      fonts:
        - asset: assets/fonts/Solway-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
  assets:
    - assets/img/weather/
